name: Pronto

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pronto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout base branch
        run: git checkout ${{ github.base_ref }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install pronto
          gem install pronto-rubocop  # Add other pronto runners as needed
          gem install faraday-retry

      - name: Run Pronto with verbose logging
        run: |
          PRONTO_PULL_REQUEST_ID="$(jq --raw-output .number "$GITHUB_EVENT_PATH")" \
          PRONTO_GITHUB_ACCESS_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          pronto run -v -f github_status github_pr -c origin/${{ github.base_ref }}
